In [ ]:
import pandas as pd
import numpy as np
alcohol = pd.read_csv('https://andybek.com/pandas-drinks', usecols=['country', 'wine_servings'], index_col=['country'], squeeze=True)

In [ ]:
# Al contrario de isnull(), el método notnull() refresa True si el valor es no nan
alcohol.notnull()

country
Afghanistan    False
Albania         True
Algeria         True
Andorra         True
Angola          True
               ...
Venezuela       True
Vietnam         True
Yemen          False
Zambia          True
Zimbabwe        True
Name: wine_servings, Length: 193, dtype: bool

In [ ]:
# Al igual que isnull pudemos usarlo para enmascarar la Serie o Dataframe.
# A modo de ilustración usamos loc que nos permite hacer selecciones con valores booleanos

# a.lcohol[alcohol.notnull()]
alcohol.loc[alcohol.notnull()]

country
Albania               54.0
Algeria               14.0
Andorra              312.0
Angola                45.0
Antigua & Barbuda     45.0
                     ...
Vanuatu               11.0
Venezuela              3.0
Vietnam                1.0
Zambia                 4.0
Zimbabwe               4.0
Name: wine_servings, Length: 162, dtype: float64

In [ ]:
# Buscamos cuántos registros no tienen valores nan

alcohol.notnull().sum()

162

In [ ]:
# al sumar los resultados de notnull e isnull deberíamos obtener la totalidad de elementos en la Serie
alcohol.notnull().sum() + alcohol.isnull().sum() == alcohol.size

True

In [ ]:
import pandas as pd
import numpy as np
alcohol = pd.read_csv('https://andybek.com/pandas-drinks', usecols=['country', 'wine_servings'], index_col=['country'], squeeze=True)